### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by mmuellersoppart** [mmuellersoppart/slog#2]
Create a config file that allows the user to save the db url and which fields they'd like to submit information for. 

Also allow the app to edit the yaml or at least show the user.

```yaml
DATABASE_URL:  <url>
INCLUDE_IS_STRESS: <y/n>
INCLUDE_IS_SLEEP_RITUAL: <y/n>
...
```
